import React, { createContext, useContext, useState, useEffect } from 'react';

type Lang = 'pt' | 'en';

const translations: Record<Lang, Record<string, string>> = {
  pt: {
    home: 'Home',
    collections: 'Coleções',
    search: 'Busca',
    cart: 'Carrinho',
    profile: 'Perfil',
    login: 'Login',
    logout: 'Sair',
    button_menu: 'Menu',
    button_toggle_language: 'Alternar idioma',
    enter: 'Entre',
    email: 'Email',
    password: 'Senha',
    forgot_password: 'Esqueci minha senha',
    no_account: 'Não tenho conta',
    have_account: 'Já tenho conta',
    register: 'Cadastre-se',
    name: 'Nome Completo',
    confirm_password: 'Repita a Senha',
    address: 'Endereço',
    cep: 'CEP',
    street: 'Rua',
    number: 'Número',
    neighborhood: 'Bairro',
    city: 'Cidade',
    state: 'Estado',
    profile_picture: 'Foto de Perfil',
    click_add_profile: 'Clique para adicionar foto de perfil',
    register_success: '✅ Conta criada com sucesso! Redirecionando para o login...',
    login_success: 'Login realizado com sucesso! ✅',
    invalid_email: 'Por favor, insira um email válido.',
    passwords_not_match: 'As senhas não coincidem.',
    error_connect: 'Erro ao conectar ao servidor.',
    register_error: 'Erro ao tentar registrar.',
    section_collections: 'Coleções',
    collection_basketball_title: 'COLEÇÃO BASQUETE',
    collection_basketball_description: 'Entre em quadra com produtos inspirados nas maiores estrelas do basquete mundial.',
    collection_athletics_title: 'COLEÇÃO ATLETISMO',
    collection_athletics_description: 'Velocidade, resistência e precisão com equipamentos feitos para atletas de alta performance.',
    collection_beachtennis_title: 'COLEÇÃO BEACH TENNIS',
    collection_beachtennis_description: 'Domine quadras e areias com produtos leves, resistentes e pensados para o jogo dinâmico.',
    collection_football_title: 'COLEÇÃO FUTEBOL',
    collection_football_description: 'Chuteiras, uniformes e acessórios ideais para elevar seu desempenho dentro das quatro linhas.',
    collection_hockey_title: 'COLEÇÃO HÓQUEI',
    collection_hockey_description: 'Equipamentos resistentes e confortáveis para encarar a intensidade do hóquei no gelo.',
    button_view: 'Vizualizar',
    button_visualize: 'Visualizar',
    featured: 'Em destaque',
    product_name: 'Nome do Produto',
    nike_max_jewell: 'Wmns Nike Max Jewell QS',
    button_buy_slide: 'Comprar',
    heading_search: 'Busque',
    placeholder_search_products: 'Buscar produtos',
    heading_filters: 'Filtros',
    button_clear_filters: 'Limpar Filtros',
    heading_category: 'Categoria',
    option_footwear: 'Calçado',
    option_ball: 'Bola',
    option_clothes: 'Roupa',
    option_accessory: 'Acessório',
    option_other: 'Outro',
    heading_sport: 'Modalidade',
    option_football_sport: 'Futebol',
    option_basketball_sport: 'Basquetebol',
    option_volleyball_sport: 'Voleibol',
    option_futsal: 'Futsal',
    option_other_sports: 'Outros',
    heading_price_filter: 'Preço',
    option_all_prices: 'Todos os preços',
    option_price_0_50: 'entre 0-50 BRL',
    option_price_50_250: 'entre 50-250 BRL',
    option_price_250_500: 'entre 250-500 BRL',
    option_price_above_500: 'acima de 500 BRL',
    button_search_filter: 'Buscar',
    message_loading_products_search: 'Carregando produtos...',
    message_no_results: 'Nenhum produto encontrado.',
    button_add_to_cart: 'Adicionar ao Carrinho',
    button_add_to_cart_product_card: 'Adicionar ao Carrinho',
    button_add_to_cart_card: 'Adicionar no Carrinho',
    button_add_to_cart_cardcart: 'Adicionar ao Carrinho',
    message_invalid_product: 'Produto inválido',
    message_no_products: 'Nenhum produto encontrado.',
    message_no_products_search: 'Nenhum produto encontrado.',
    message_empty_cart: '🛒 Seu carrinho está vazio.',
    message_add_products_to_continue: 'Adicione alguns produtos para continuar!',
    label_subtotal: 'Subtotal',
    label_shipping: 'Frete',
    placeholder_promo_code: 'Adicionar Cupom Promocional',
    button_verify_coupon: 'Verificar',
    label_total: 'Total',
    button_checkout: 'Finalizar',
    button_continue_shopping: 'Escolher Mais Produtos',
    message_estimated_delivery_time: 'Prazo de Entrega estimado - Entre 15 - 45 dias da data do pedido',
    heading_payment_method: 'Método de Pagamento',
    label_credit_card: 'Cartão de Crédito',
    label_pix: 'PIX',
    label_card_number: 'Número do Cartão',
    placeholder_card_number: '0000 0000 0000 0000',
    label_card_name: 'Nome no Cartão',
    placeholder_card_name: 'Nome como está no cartão',
    label_expiry_date: 'Validade',
    placeholder_expiry_date: 'MM/AA',
    label_cvv: 'CVV',
    placeholder_cvv: '123',
    label_installments: 'Parcelamento',
    option_payment_cash: 'À vista',
    button_finalize_purchase: 'Finalizar Compra',
    heading_pix_code: 'Código PIX',
    button_copy_pix_code: 'Copiar Código PIX',
    instruction_open_bank_app: 'Abra o aplicativo do seu banco',
    instruction_choose_pix_option: 'Escolha a opção PIX',
    instruction_paste_code: 'Cole o código acima',
    instruction_confirm_payment: 'Confirme o pagamento de',
    instruction_return_and_finalize: 'Volte aqui e clique em "Finalizar Compra"',
    heading_order_confirmed: 'Pedido Confirmado!',
    message_order_success: 'Seu pedido foi realizado com sucesso e está sendo processado.',
    heading_order_details: 'Detalhes do Pedido',
    label_order_number: 'Número do Pedido:',
    label_date: 'Data:',
    label_payment_method_details: 'Método de Pagamento:',
    label_credit_card_payment_confirmation: 'Cartão de Crédito',
    label_total_confirmation: 'Total:',
    label_status: 'Status:',
    label_processing_status: 'Processando',
    message_email_sent_confirmation: 'Enviamos um e-mail com os detalhes da sua compra para confirmação.',
    button_continue_shopping_confirmation: 'Continuar Comprando',
    label_quantity: 'Quantidade',
    button_decrease_quantity: 'Diminuir quantidade',
    button_increase_quantity: 'Aumentar quantidade',
    label_product_category: 'Chuteira',
    label_product_title: 'England Pack Umbro',
    label_size: 'Tamanho:',
    label_type: 'Tipo:',
    label_color: 'Cor:',
    label_price: 'Valor:',
    button_buy_now: 'Comprar Agora',
    heading_support: 'Suporte',
    link_customer_service: 'Atendimento ao cliente',
    link_payment_methods: 'Formas de pagamento',
    link_faq: 'Dúvidas frequentes',
    link_cookies: 'Cookies',
    heading_tabs: 'Abas',
    link_footer_login: 'Login',
    link_footer_collections: 'Coleções',
    link_footer_search: 'Busca',
    link_footer_cart: 'Carrinho',
    heading_contact_us: 'Contate-nos',
    link_email: 'once11@gmail.com',
    text_address: 'Av. Bahia, 1739 - Indaiá, Caraguatatuba - SP, Brazil, 11665-310',
    link_phone: '+55 12 99170-9082',
    heading_follow_us: 'Siga-nos',
    link_youtube: 'Youtube',
    link_instagram: 'Instagram',
    link_twitter: 'X',
    heading_about_once: 'Sobre a ONCE',
    paragraph_about_once_description: 'Somos um marketplace de produtos esportivos que reúne variedade, qualidade e praticidade em um só lugar. Nosso propósito é conectar apaixonados por esporte a opções que unem desempenho, estilo e conforto, garantindo sempre segurança e confiança em cada compra.',
    heading_campaign: 'Campanha',
    heading_we_will_all_winners: 'Seremos Todos Vencedores',
    heading_winners: 'Vencedores',
    paragraph_campaign_description: '1,4 bilhão de crianças com idade entre 0-15 anos não têm nenhuma forma de proteção social básica. Por isso, a ONCE em parceria com a UNICEF, ILO e Save the Children, está realizando uma ação de caridade, onde você pode contribuir.',
    heading_how: 'Como',
    heading_you_emphasis: 'VOCÊ',
    heading_can_help: 'pode ajudar',
    heading_stories: 'Histórias',
    heading_inspiring: 'Inpiradores',
    heading_athlete_oluwakemi: 'Oluwakemi',
    heading_athlete_musa: 'Musa',
    paragraph_athlete_oluwakemi_story: 'Oluwakemi Musa cresceu nas ruas de Lagos, envolvida com gangues e distante da escola. Foi levada pela polícia a um centro de reabilitação apoiado pelo UNICEF, onde recebeu acolhimento, educação e treinamento profissional. Longe das ruas, reencontrou o basquete e transformou sua vida. Competiu nos Special Olympics em Chicago e Abu Dhabi, tornando-se Embaixadora das Special Olympics Nigéria. Hoje inspira outros jovens, provando que até na miséria pode germinar grandeza — basta uma oportunidade para florescer.',
    heading_athlete_rafaela: 'Rafaela',
    heading_athlete_silva: 'Silva',
    paragraph_athlete_rafaela_story: 'Rafaela Silva nasceu na favela da Cidade de Deus, no Rio de Janeiro, cercada por violência e pobreza. Desde pequena, seus pais a colocaram no Instituto Reação, projeto de judô que oferecia disciplina, educação e oportunidades. Transformando sua força e raiva em foco, Rafaela conquistou títulos nacionais e internacionais, culminando com o ouro olímpico no Rio‑2016. Sua trajetória é exemplo de superação, mostrando que apoio, talento e determinação podem transformar adversidade em conquista.',
    heading_athlete_vinicius: 'Vinícius R.',
    heading_athlete_bento: 'Bento',
    paragraph_athlete_vinicius_story: 'Vinícius Rodrigues Bento, natural de Primavera (SP) e criado em Maringá (PR), sofreu um acidente de moto aos 19 anos que resultou na amputação de sua perna direita. Enfrentando limitações financeiras, encontrou no esporte paralímpico uma nova chance de vida. Com apoio do Programa Bolsa Atleta, treinou e competiu em alto nível, conquistando a medalha de prata nos 100 metros T63 nos Jogos Paralímpicos de Tóquio‑2020 e estabelecendo recordes mundiais. Sua história é exemplo de superação e resiliência frente à adversidade.',
    heading_your_turn: 'Agora é sua vez',
    paragraph_campaign_message: 'A campanha não entrega apenas equipamentos, entrega oportunidades. Cada bola, cada raquete, cada par de tênis representa a possibilidade de que uma criança em situação de vulnerabilidade descubra seu talento, encontre disciplina, confiança e até uma nova trajetória de vida, assim como Rafaela, Oluwakemi e Vinícius. Ao apoiar o Seremos Todos Vencedores, cada doação se transforma em um passo para mudar histórias, abrir portas e mostrar que, com acesso ao esporte, qualquer criança pode superar obstáculos aparentemente intransponíveis.',
    button_donate: 'Doar',
    heading_featured_products: 'Produtos em Destaque',
    product_bmw_m3_competition: 'BMW M3 Competition',
    product_bmw_m3_subtitle: 'Twin-Turbo Inline-6 Performance',
    product_lamborghini_huracan: 'Lamborghini Huracán',
    product_lamborghini_subtitle: 'Naturally Aspirated V10 Excellence',
    product_ferrari_sf90: 'Ferrari SF90 Stradale',
    product_ferrari_subtitle: 'Plug-in Hybrid Revolution',
    product_porsche_911: 'Porsche 911 Turbo S',
    product_porsche_subtitle: 'Twin-Turbo Flat-Six Perfection',
    button_buy: 'Comprar',
    heading_more_products: 'Mais produtos',
    heading_featured_products_reds: 'Produtos em Destaque',
    product_bmw_m3_reds: 'BMW M3 Competition',
    product_bmw_m3_subtitle_reds: 'Twin-Turbo Inline-6 Performance',
    product_lamborghini_reds: 'Lamborghini Huracán',
    product_lamborghini_subtitle_reds: 'Naturally Aspirated V10 Excellence',
    product_ferrari_reds: 'Ferrari SF90 Stradale',
    product_ferrari_subtitle_reds: 'Plug-in Hybrid Revolution',
    product_porsche_reds: 'Porsche 911 Turbo S',
    product_porsche_subtitle_reds: 'Twin-Turbo Flat-Six Perfection',
    button_buy_reds: 'Comprar',
    heading_more_products_reds: 'Mais produtos',
    product_basketball_shoe_a: 'Tênis Basquete A',
    product_basketball_shoe_a_description: 'O melhor tênis para quadras indoor.',
    product_team_shirt_b: 'Camisa Time B',
    product_team_shirt_b_description: 'Camisa oficial da temporada 2024.',
    product_official_ball_c: 'Bola Oficial C',
    product_official_ball_c_description: 'Bola de basquete com grip profissional.',
    product_shorts_d: 'Shorts D',
    product_shorts_d_description: 'Shorts leve e respirável para jogos.',
    product_sock_e: 'Meia E',
    product_sock_e_description: 'Meias de compressão para alta performance.',
    product_protector_f: 'Protetor F',
    product_protector_f_description: 'Protetor bucal essencial para o jogo.',
    category_clothes: 'Roupas',
    section_creative_elements: 'Creative Elements',
    category_footwear: 'Calçados',
    section_inner_stillness: 'Inner Stillness',
    category_balls: 'Bolas',
    section_deep_knowing: 'Deep Knowing',
    category_accessories: 'Acessórios',
    section_true_expression: 'True Expression',
    category_equipment: 'Equipamentos',
    section_now_moment: 'Now Moment',
    category_collectibles: 'Colecionáveis',
    section_deep_attention: 'Deep Attention',
    heading_welcome_to: 'Bem-vindo a',
    heading_once_11: 'ONCE 11',
    button_login: 'Login',
    alt_text_lebron: 'Lebron James',
    alt_text_basketball_player: 'Jogador de Basquete',
    alt_text_athletics_player: 'Atleta de Atletismo',
    alt_text_beachtennis_player: 'Jogador de Beach Tennis',
    alt_text_football_player: 'Jogador de Futebol',
    alt_text_hockey_player: 'Jogador de Hóquei',
    alt_text_slide_0: 'slide-0',
    alt_text_slide_1: 'slide-1',
    alt_text_slide_2: 'slide-2',
    alt_text_slide_3: 'slide-3',
    alt_text_slide_4: 'slide-4',
    alt_text_product_shoe: 'Tênis Nike verde com detalhes em branco e preto, design esportivo e moderno, ideal para uso casual ou prática esportiva.',
    alt_text_basketball_404: 'Bola de basquete',
    alt_text_football_player_banner: 'Jogador de Futebol',
    alt_text_about_player: 'Jogador representando a ONCE 11 - Marketplace de produtos esportivos',
    alt_text_golden_shoe: 'Tênis Dourado',
    heading_error_404: '404 - Página Fora de Jogo',
    message_loading_products: 'Carregando produtos...',
    message_products_load_error: 'Falha ao carregar os produtos. Verifique a conexão com o backend.',
    heading_collection_prefix: 'Col',
    heading_collection_highlight: 'e',
    heading_collection_suffix: 'ção',
    heading_we_will_all: 'Seremos todos',
    heading_be_winners: 'vencedores.',
    button_view_campaign: 'Visualizar',
  },
  en: {
    home: 'Home',
    collections: 'Collections',
    search: 'Search',
    cart: 'Cart',
    profile: 'Profile',
    login: 'Login',
    logout: 'Logout',
    button_menu: 'Menu',
    button_toggle_language: 'Toggle language',
    enter: 'Sign in',
    email: 'Email',
    password: 'Password',
    forgot_password: 'Forgot password',
    no_account: "Don't have an account",
    have_account: 'Already have an account',
    register: 'Register',
    name: 'Full Name',
    confirm_password: 'Repeat Password',
    address: 'Address',
    cep: 'Postal Code',
    street: 'Street',
    number: 'Number',
    neighborhood: 'Neighborhood',
    city: 'City',
    state: 'State',
    profile_picture: 'Profile Picture',
    click_add_profile: 'Click to add profile picture',
    register_success: '✅ Account created successfully! Redirecting to login...',
    login_success: 'Successfully logged in! ✅',
    invalid_email: 'Please enter a valid email address.',
    passwords_not_match: 'Passwords do not match.',
    error_connect: 'Error connecting to server.',
    register_error: 'Error trying to register.',
    section_collections: 'Collections',
    collection_basketball_title: 'BASKETBALL COLLECTION',
    collection_basketball_description: 'Get on the court with products inspired by the biggest basketball stars in the world.',
    collection_athletics_title: 'ATHLETICS COLLECTION',
    collection_athletics_description: 'Speed, endurance and precision with equipment made for high performance athletes.',
    collection_beachtennis_title: 'BEACH TENNIS COLLECTION',
    collection_beachtennis_description: 'Dominate courts and sand with light, resistant products designed for dynamic play.',
    collection_football_title: 'FOOTBALL COLLECTION',
    collection_football_description: 'Boots, uniforms and accessories designed to boost your performance on the pitch.',
    collection_hockey_title: 'HOCKEY COLLECTION',
    collection_hockey_description: 'Durable and comfortable equipment to tackle the intensity of ice hockey.',
    button_view: 'View',
    button_visualize: 'Visualize',
    featured: 'Featured',
    product_name: 'Product Name',
    nike_max_jewell: 'Wmns Nike Max Jewell QS',
    button_buy_slide: 'Buy',
    heading_search: 'Search',
    placeholder_search_products: 'Search products',
    heading_filters: 'Filters',
    button_clear_filters: 'Clear Filters',
    heading_category: 'Category',
    option_footwear: 'Footwear',
    option_ball: 'Ball',
    option_accessory: 'Accessory',
    option_other: 'Other',
    heading_sport: 'Sport',
    option_football_sport: 'Football',
    option_basketball_sport: 'Basketball',
    option_volleyball_sport: 'Volleyball',
    option_futsal: 'Futsal',
    option_other_sports: 'Other',
    heading_price_filter: 'Price',
    option_all_prices: 'All prices',
    option_price_0_50: 'between 0-50 BRL',
    option_price_50_250: 'between 50-250 BRL',
    option_price_250_500: 'between 250-500 BRL',
    option_price_above_500: 'above 500 BRL',
    button_search_filter: 'Search',
    message_loading_products_search: 'Loading products...',
    message_no_results: 'No products found.',
    button_add_to_cart: 'Add to Cart',
    button_add_to_cart_product_card: 'Add to Cart',
    button_add_to_cart_card: 'Add to Cart',
    button_add_to_cart_cardcart: 'Add to Cart',
    message_invalid_product: 'Invalid product',
    message_no_products: 'No products found.',
    message_no_products_search: 'No products found.',
    message_empty_cart: '🛒 Your cart is empty.',
    message_add_products_to_continue: 'Add some products to continue!',
    label_subtotal: 'Subtotal',
    label_shipping: 'Shipping',
    placeholder_promo_code: 'Add Promotional Code',
    button_verify_coupon: 'Verify',
    label_total: 'Total',
    button_checkout: 'Checkout',
    button_continue_shopping: 'Choose More Products',
    message_estimated_delivery_time: 'Estimated Delivery Time - Between 15 - 45 days from order date',
    heading_payment_method: 'Payment Method',
    label_credit_card: 'Credit Card',
    label_pix: 'PIX',
    label_card_number: 'Card Number',
    placeholder_card_number: '0000 0000 0000 0000',
    label_card_name: 'Cardholder Name',
    placeholder_card_name: 'Name as it appears on card',
    label_expiry_date: 'Expiry Date',
    placeholder_expiry_date: 'MM/YY',
    label_cvv: 'CVV',
    placeholder_cvv: '123',
    label_installments: 'Installments',
    option_payment_cash: 'Full payment',
    button_finalize_purchase: 'Complete Purchase',
    heading_pix_code: 'PIX Code',
    button_copy_pix_code: 'Copy PIX Code',
    instruction_open_bank_app: 'Open your bank app',
    instruction_choose_pix_option: 'Choose the PIX option',
    instruction_paste_code: 'Paste the code above',
    instruction_confirm_payment: 'Confirm payment of',
    instruction_return_and_finalize: 'Come back here and click "Complete Purchase"',
    heading_order_confirmed: 'Order Confirmed!',
    option_clothes: 'Clothes',
    message_order_success: 'Your order has been successfully placed and is being processed.',
    heading_order_details: 'Order Details',
    label_order_number: 'Order Number:',
    label_date: 'Date:',
    label_payment_method_details: 'Payment Method:',
    label_credit_card_payment_confirmation: 'Credit Card',
    label_total_confirmation: 'Total:',
    label_status: 'Status:',
    label_processing_status: 'Processing',
    message_email_sent_confirmation: 'We sent an email with the details of your purchase for confirmation.',
    button_continue_shopping_confirmation: 'Continue Shopping',
    label_quantity: 'Quantity',
    button_decrease_quantity: 'Decrease quantity',
    button_increase_quantity: 'Increase quantity',
    label_product_category: 'Boot',
    label_product_title: 'England Pack Umbro',
    label_size: 'Size:',
    label_type: 'Type:',
    label_color: 'Color:',
    label_price: 'Price:',
    button_buy_now: 'Buy Now',
    heading_support: 'Support',
    link_customer_service: 'Customer Service',
    link_payment_methods: 'Payment Methods',
    link_faq: 'Frequently Asked Questions',
    link_cookies: 'Cookies',
    heading_tabs: 'Tabs',
    link_footer_login: 'Login',
    link_footer_collections: 'Collections',
    link_footer_search: 'Search',
    link_footer_cart: 'Cart',
    heading_contact_us: 'Contact Us',
    link_email: 'once11@gmail.com',
    text_address: 'Av. Bahia, 1739 - Indaiá, Caraguatatuba - SP, Brazil, 11665-310',
    link_phone: '+55 12 99170-9082',
    heading_follow_us: 'Follow Us',
    link_youtube: 'Youtube',
    link_instagram: 'Instagram',
    link_twitter: 'X',
    heading_about_once: 'About ONCE',
    paragraph_about_once_description: 'We are a sports products marketplace that brings together variety, quality and practicality in one place. Our purpose is to connect sports enthusiasts with options that combine performance, style and comfort, always ensuring safety and confidence in every purchase.',
    heading_campaign: 'Campaign',
    heading_we_will_all_winners: 'We Will All Be Winners',
    heading_winners: 'Winners',
    paragraph_campaign_description: '1.4 billion children aged 0-15 have no form of basic social protection. That\'s why ONCE, in partnership with UNICEF, ILO and Save the Children, is carrying out a charity initiative where you can contribute.',
    heading_how: 'How',
    heading_you_emphasis: 'YOU',
    heading_can_help: 'can help',
    heading_stories: 'Stories',
    heading_inspiring: 'Inspiring',
    heading_athlete_oluwakemi: 'Oluwakemi',
    heading_athlete_musa: 'Musa',
    paragraph_athlete_oluwakemi_story: 'Oluwakemi Musa grew up on the streets of Lagos, involved with gangs and away from school. She was taken by police to a rehabilitation center supported by UNICEF, where she received care, education and professional training. Away from the streets, she rediscovered basketball and transformed her life. She competed in the Special Olympics in Chicago and Abu Dhabi, becoming an Ambassador for Special Olympics Nigeria. Today she inspires other young people, proving that even in misery, greatness can germinate — it takes just one opportunity to flourish.',
    heading_athlete_rafaela: 'Rafaela',
    heading_athlete_silva: 'Silva',
    paragraph_athlete_rafaela_story: 'Rafaela Silva was born in the slums of Cidade de Deus in Rio de Janeiro, surrounded by violence and poverty. From a young age, her parents placed her at Instituto Reação, a judo project that offered discipline, education and opportunities. Transforming her strength and anger into focus, Rafaela won national and international titles, culminating in Olympic gold at Rio 2016. Her trajectory is an example of overcoming, showing that support, talent and determination can transform adversity into achievement.',
    heading_athlete_vinicius: 'Vinícius R.',
    heading_athlete_bento: 'Bento',
    paragraph_athlete_vinicius_story: 'Vinícius Rodrigues Bento, from Primavera (SP) and raised in Maringá (PR), suffered a motorcycle accident at age 19 that resulted in the amputation of his right leg. Facing financial limitations, he found in paralympic sports a new chance at life. With support from the Athlete Grant Program, he trained and competed at the highest level, winning the silver medal in the 100 meters T63 at the Tokyo 2020 Paralympic Games and setting world records. His story is an example of overcoming and resilience in the face of adversity.',
    heading_your_turn: 'Now it\'s your turn',
    paragraph_campaign_message: 'The campaign doesn\'t just deliver equipment, it delivers opportunities. Every ball, every racket, every pair of shoes represents the possibility that a child in a vulnerable situation will discover their talent, find discipline, confidence and even a new life path, just like Rafaela, Oluwakemi and Vinícius. By supporting We Will All Be Winners, each donation becomes a step to change stories, open doors and show that with access to sports, any child can overcome seemingly insurmountable obstacles.',
    button_donate: 'Donate',
    heading_featured_products: 'Featured Products',
    product_bmw_m3_competition: 'BMW M3 Competition',
    product_bmw_m3_subtitle: 'Twin-Turbo Inline-6 Performance',
    product_lamborghini_huracan: 'Lamborghini Huracán',
    product_lamborghini_subtitle: 'Naturally Aspirated V10 Excellence',
    product_ferrari_sf90: 'Ferrari SF90 Stradale',
    product_ferrari_subtitle: 'Plug-in Hybrid Revolution',
    product_porsche_911: 'Porsche 911 Turbo S',
    product_porsche_subtitle: 'Twin-Turbo Flat-Six Perfection',
    button_buy: 'Buy',
    heading_more_products: 'More products',
    heading_featured_products_reds: 'Featured Products',
    product_bmw_m3_reds: 'BMW M3 Competition',
    product_bmw_m3_subtitle_reds: 'Twin-Turbo Inline-6 Performance',
    product_lamborghini_reds: 'Lamborghini Huracán',
    product_lamborghini_subtitle_reds: 'Naturally Aspirated V10 Excellence',
    product_ferrari_reds: 'Ferrari SF90 Stradale',
    product_ferrari_subtitle_reds: 'Plug-in Hybrid Revolution',
    product_porsche_reds: 'Porsche 911 Turbo S',
    product_porsche_subtitle_reds: 'Twin-Turbo Flat-Six Perfection',
    button_buy_reds: 'Buy',
    heading_more_products_reds: 'More products',
    product_basketball_shoe_a: 'Basketball Shoe A',
    product_basketball_shoe_a_description: 'The best shoes for indoor courts.',
    product_team_shirt_b: 'Team Shirt B',
    product_team_shirt_b_description: 'Official shirt for the 2024 season.',
    product_official_ball_c: 'Official Ball C',
    product_official_ball_c_description: 'Basketball with professional grip.',
    product_shorts_d: 'Shorts D',
    product_shorts_d_description: 'Light and breathable shorts for games.',
    product_sock_e: 'Sock E',
    product_sock_e_description: 'Compression socks for high performance.',
    product_protector_f: 'Protector F',
    product_protector_f_description: 'Mouthguard essential for the game.',
    category_clothes: 'Clothes',
    section_creative_elements: 'Creative Elements',
    category_footwear: 'Footwear',
    section_inner_stillness: 'Inner Stillness',
    category_balls: 'Balls',
    section_deep_knowing: 'Deep Knowing',
    category_accessories: 'Accessories',
    section_true_expression: 'True Expression',
    category_equipment: 'Equipment',
    section_now_moment: 'Now Moment',
    category_collectibles: 'Collectibles',
    section_deep_attention: 'Deep Attention',
    heading_welcome_to: 'Welcome to',
    heading_once_11: 'ONCE 11',
    button_login: 'Login',
    alt_text_lebron: 'Lebron James',
    alt_text_basketball_player: 'Basketball Player',
    alt_text_athletics_player: 'Athletics Player',
    alt_text_beachtennis_player: 'Beach Tennis Player',
    alt_text_football_player: 'Football Player',
    alt_text_hockey_player: 'Hockey Player',
    alt_text_slide_0: 'slide-0',
    alt_text_slide_1: 'slide-1',
    alt_text_slide_2: 'slide-2',
    alt_text_slide_3: 'slide-3',
    alt_text_slide_4: 'slide-4',
    alt_text_product_shoe: 'Green Nike shoe with white and black details, modern sports design, ideal for casual use or sports practice.',
    alt_text_basketball_404: 'Basketball',
    alt_text_football_player_banner: 'Football Player',
    alt_text_about_player: 'Player representing ONCE 11 - Sports products marketplace',
    alt_text_golden_shoe: 'Golden Shoe',
    heading_error_404: '404 - Page Out of Play',
    message_loading_products: 'Loading products...',
    message_products_load_error: 'Failed to load products. Check your connection with the backend.',
    heading_collection_prefix: 'Col',
    heading_collection_highlight: 'e',
    heading_collection_suffix: 'ction',
    heading_we_will_all: 'We will all',
    heading_be_winners: 'be winners.',
    button_view_campaign: 'View',
  }
};

interface LanguageContextType {
  lang: Lang;
  toggleLang: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>('pt');
  const [, setRender] = useState(0); // Força re-render global

  useEffect(() => {
    const stored = localStorage.getItem('lang') as Lang | null;
    if (stored === 'pt' || stored === 'en') setLang(stored);
  }, []);

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const toggleLang = () => {
    setLang((l) => (l === 'pt' ? 'en' : 'pt'));
    setRender(prev => prev + 1); // Força re-render de toda a árvore
  };

  const t = (key: string) => {
    return translations[lang][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};

export const useTranslation = () => {
  const { t } = useLanguage();
  return t;
};

export default LanguageContext;
